spring:
  datasource:
    url: jdbc:h2:mem:mioDb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /all/console
  jpa:
    defer-datasource-initialization: true